### PR TITLE
Darken sub-label text

### LINKED ISSUE #38: Contact Info Optional Text not visible against light blue background
Could just be my screen, but I would prefer if the "Optional: in case ..." text contrasted a bit more against the background, especially if folks are filling out the form outside or in bright light.
image

### PR DESCRIPTION
**Pull request by christopherstyles**
Does this work?

votetracker

Closes #38

### CODE REVIEW

**Comment by gnarf** [comment]
So Sorry @christopherstyles --- I started working on these so recently, I wasn't expecting to see commits coming in at 5am :(  --- Also I just completely glanced over the lines in the issue description... 

Thank you SO MUCH for trying to help with these last things, and would appreciate any other help.

**Comment by christopherstyles** [comment]
Ah okay, no problem ;)

**Comment by gnarf** [comment]
<--- fail maintainer on no sleep and WAY TOO MUCH COFFEE!!!!

Go BERNIE! :)

**Comment by christopherstyles** [comment]
haha, fair enough!

**Pull request closed without merging**
