### PR TITLE
Adding status message to notify user of submit success

### PR DESCRIPTION
**Pull request by kav**
-might consider adding a timestamp
-needs some visual work…
-some choices made to better support errors later
    (if over tern, var over inline)

### CODE REVIEW

**Comment by gnarf** [comment]
I think you might need to add `submitted: true` to the `submitted()` on `submittable.jsx`

I think you might also want to add a `change` event listener in `trackForm` that would unset that state when they "tweak" a value ---

The Caucus Reporting would only go to "thank you" on the "final report" for instance, so when they change a value, it could unset submitted.

Maybe also, keep `submit` disabled while in the `submitted` state?

**Comment by kav** [comment]
Ah, yes missed those when trying to separate changes. Will fix that now.

I figured the message that the submit was successful should help there. Do you want them submitting the same thing at a later time perhaps to indicate no change?

**Comment by gnarf** [comment]
So there shouldn't be a "no change" submission I don't think.

It should basically stay on the form, and once they mutate to "second report" or change a number, they can submit again? That's what I'm thinking here.

**Comment by gnarf** [comment]
Looks like this might need a rebase now (sorry we added something to send to thank you)

**Comment by kav** [comment]
merged

**Pull request merged**
